In [13]:
import numpy as np
x = [1,2,3,4]
nx =np.array(x)


In [14]:
y = np.array([1,2,3,4,5])

In [16]:
print(y.ndim) # dimension count
print(y.shape) # shape of aary
print(y.size) # element count

1
(5,)
5


In [19]:
z = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(z.ndim) # dimension count
print(z.shape) # shape of aary
print(z.size) # element count
print(z)

2
(3, 3)
9
[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [ ]:
a = np.arange(10,100,.1)
#print(a)
print(a.size)
a2 = a.reshape((30,30))
#print(a2)
a3 = a.reshape((30,15,2))
#print(a3)
b = np.linspace(1,10,100)
print(b)


In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)
#print(a+b)
#print(a*b)
#print(a>b)
#print(a<b)
# print(a.max())
# print(a.mean())
# print(a.min())
# print(a.std())
# print(a.sum())
print(a.max(axis =0))  # columwise calculate
print(a.max(axis=1))   # rowwise calculate

In [39]:
t= np.arange(-np.pi*3,np.pi,.05)
x = np.sin(t)
y = np.cos(t)
#print(t)
#print(x)
#print(y)
np.pi


3.141592653589793

In [ ]:
import matplotlib.pyplot as plt
plt.plot(t,x,'r--o')
plt.plot(t,y,'g:x')
plt.title("visulization")
plt.show()

In [2]:
import numpy as np
x = np.random.randint(1,100,(6,6))
print(x)


[[25 22  3 74 12  6]
 [47 95 15 24 46 78]
 [22 86 91 34 48 30]
 [99  7 42 76 18 93]
 [39 22 41 23 79 95]
 [17 87 84  9  3 45]]


In [3]:
x[0]

array([25, 22,  3, 74, 12,  6])

In [4]:
x[:,0] # first column

array([25, 47, 22, 99, 39, 17])

In [5]:
x[:,4]

array([12, 46, 48, 18, 79,  3])

In [14]:
b = np.array ([[1,2,3,4],[6,4,2,2],[2,3,4,3],[1,2,4,1]])
print(b)

[[1 2 3 4]
 [6 4 2 2]
 [2 3 4 3]
 [1 2 4 1]]


In [15]:
print(b[1:,0:3])

[[6 4 2]
 [2 3 4]
 [1 2 4]]
